# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7eb2bb657072d21d9aa17ce344d722460739f2b82052cb84775201d765c568b4aeaeaaafe544ff57d98035b1dccb80158d10ec264a7340c413e449c77883897

test:
  secret_key_base: 886fe1eb8becb8d361cebfc00e53dde7b118b2b2f33fd207834db15c32fa6fbeb895c30c66e0c1638c36b743b197e4902eae6a28a5b2a22c3b7acd7146fdaec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
